name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: ilammy/msvc-dev-cmd@v1
    
    - name: Compile step 1
      run: cl.exe /c /EHsc /MT /O2 /DNDEBUG /DUNICODE src/main.cpp /Fosrc/main.obj
    
    - name: Compile step 2  
      run: link.exe src/main.obj kernel32.lib user32.lib comctl32.lib gdi32.lib psapi.lib shell32.lib ole32.lib /OUT:executor.exe /SUBSYSTEM:WINDOWS
    
    - uses: actions/upload-artifact@v4
      with:
        name: Executor
        path: executor.exe
